# Generated by Django 4.2.3 on 2023-10-18 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=404)),
                ('cooking_steps', models.CharField(max_length=404)),
                ('cooking_time_in_seconds', models.IntegerField()),
                ('photo_of_the_dish', models.ImageField(upload_to='my_gallery')),
                ('autor', models.CharField(max_length=50)),
                ('average_price_in_restaurants', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ToLinkRecipesAndCategories',
            fields=[
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='working_with_recipes.recipe')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='working_with_recipes.recipecategories')),
            ],
        ),
    ]
