# Generated by Django 4.2.3 on 2023-10-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_with_recipes', '0002_alter_recipe_photo_of_the_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo_of_the_dish',
            field=models.ImageField(upload_to='my_gallery'),
        ),
    ]
